spring:
  profiles: 
    active: localdb

server:
  port: 18081
  servlet:
    context-path: /sec-server

logging:
  level:
    root: INFO
    com.psys.hobb: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
            mvc.method.annotation.ervletInvocableHandleMethod: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              BasicExtractor: TRACE
        engine:
          QueryParameters: TRACE
          query:
            HQLQueryPlan: TRACE